export const ADD_TODO = 'ADD_TODO'
export const CHANGE_CURRENT_TODO_VALUE = 'CHANGE_CURRENT_TODO_VALUE'
export const CHANGE_TODO_CHECKBOX = 'CHANGE_TODO_CHECKBOX'
export const DELETE_TODO = 'DELETE_TODO'
export const DELETE_ALL_TODO = 'DELETE_ALL_TODO'

export const GET_CARS_BRANDS = 'GET_CARS_BRANDS'
export const GET_CURRENT_BRAND = 'GET_CURRENT_BRAND'