export const SET_CURRENT_TODOS = 'SET_TODOS'
export const SET_COMPLETED_TODOS = 'SET_COMPLETED_TODOS'
export const CURRENT_TODO = 'CURRENT_TODO'
export const DELETE_ALL_TODOS = 'DELETE_ALL_TODOS'
export const ADD_CURRENT_TODO = 'ADD_CURRENT_TODO'
export const ADD_COMPLETED_TODO = 'ADD_COMPLETED_TODO'
export const DELETE_COMPLETED_TODO = 'DELETE_COMPLETED_TODO'


export const GET_BRANDS = 'GET_BRANDS'
export const GET_CARS = 'GET_CARS'
export const SHOP_LOADING_START = 'SHOP_LOADING_START'
export const SHOP_LOADING_FINISH = 'SHOP_LOADING_FINISH'
export const GET_CURRENT_CAR = 'GET_CURRENT_CAR'
export const ADD_TO_SHOPPING_CART = 'ADD_TO_SHOPPING_CART'
export const DELETE_WITH_SHOPPING_CART = 'DELETE_WITH_SHOPPING_CART'


export const SET_USER = 'SET_USER'
export const LOGOUT = 'LOGOUT'