export const LOGOUT_TODOS = 'LOGOUT_TODOS'
export const SET_TODOS = 'SET_TODOS'
export const CURRENT_TODO_VALUE = 'CURRENT_TODO_VALUE'
export const ADD_TODO = 'ADD_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const DELETE_DELETED_TODO = 'DELETE_DELETED_TODO'
export const SET_DELETED_TODOS = 'SET_DELETED_TODOS'
export const CHANGE_COMPLETE = 'CHANGE_COMPLETE'


export const START_LOADING = 'START_LOADING'
export const END_LOADING = 'END_LOADING'


export const GET_BRANDS = 'GET_BRANDS'
export const GET_CARS = 'GET_CARS'
export const SHOP_LOADING_START = 'SHOP_LOADING_START'
export const SHOP_LOADING_FINISH = 'SHOP_LOADING_FINISH'
export const GET_CURRENT_CAR = 'GET_CURRENT_CAR'
export const ADD_TO_SHOPPING_CART = 'ADD_TO_SHOPPING_CART'
export const DELETE_WITH_SHOPPING_CART = 'DELETE_WITH_SHOPPING_CART'


export const SET_USER = 'SET_USER'
export const LOGOUT = 'LOGOUT'


export const CNANGE_FIELD = 'CNANGE_FIELD'